"use strict";

const config = JSON.parse(process.env.ENV);

config.illustrations = [
  {"id": ["2y7", "2g4trng925g"], "category": "original", "title": "小さな手"},
  {"id": ["mte", "1djeozlm2g8"], "category": "original", "title": "おいで"},
  {"id": ["xy1", "81tedn1nl3"], "category": "original", "title": "電車ごっこ"},
  {"id": ["s3y", "216mwxbf2jt"], "category": "original", "title": "リスカ"},
  {"id": ["mnf", "19l2e4hn7vg"], "category": "original", "title": "自我像"},
  {"id": ["s3j", "hgt60zx3djk"], "category": "original", "title": "五月蝿い"},
  {"id": ["iah", "qauuwle3zq8"], "category": "original", "title": "床屋さんごっこ"},
  {"id": ["sof", "hleawuwpibs"], "category": "original", "title": "観察"},
  {"id": ["u7k", "avn67yud77s"], "category": "original", "title": "見つけた"},
  {"id": ["6sf", "m9pli2yumpc"], "category": "original", "title": "しっぽ"},
  {"id": ["w02", "jlbejkl6ogo"], "category": "original", "title": "tree"},
  {"id": ["e8z", "iddozoi4g60"], "category": "original", "title": "こんにちは"},
  {"id": ["8oa", "4yxuk40ee1o"], "category": "original", "title": "知ってるよ"},
  {"id": ["xw8", "7finhst45ck"], "category": "original", "title": "スマイル"},
  {"id": ["3z2", "pr8lunvgedc"], "category": "original", "title": "サンタクロース"},
  {"id": ["2hg", "jnt6wj1ww40"], "category": "original", "title": "天使"},
  {"id": ["1pq", "aio4havwr34"], "category": "original", "title": "マスク"},
  {"id": ["ynl", "cxb7rci6myo"], "category": "original", "title": "横目がちな少女"},
  {"id": ["xdp", "cm5gk0fuftc"], "category": "original", "title": "自殺観念"},
  {"id": ["4ab", "ah2ju5lcmxs"], "category": "original", "title": "蝶々"},
  {"id": ["k0j", "ek8rbse1g94"], "category": "original", "title": "ふわふわ"},
  {"id": ["ee5", "nrp6mp8ex68"], "category": "original", "title": "イタズラ"},
  {"id": ["g36", "gpzndn6ljq8"], "category": "original", "title": "座標軸エス"},
  {"id": ["1r1", "a69v9wt8kc0"], "category": "original", "title": "世界"},
  {"id": ["hr5", "2ra2wtwusakg"], "category": "original", "title": "まんじゅうこわい"},
  {"id": ["9mh", "6o5ym4yud400"], "category": "original", "title": "あまやどり"},
  {"id": ["a0k", "7rhrbxpr7ug"], "category": "original", "title": "繋がる"},
  {"id": ["yib", "5iecxhthbj0g"], "category": "original", "title": "点滴"},
  {"id": ["3ch", "2bg9j0ie1zfo"], "category": "original", "title": "部屋"},
  {"id": ["shi", "4swaxyt41da8"], "category": "original", "title": "落とし穴"},
  {"id": ["98d", "1rojhfj5klj4"], "category": "original", "title": "うつうつ"},
  {"id": ["fgj", "38xqvfwn34is"], "category": "original", "title": "風船"},
  {"id": ["xy9", "5e86x19vcjgg"], "category": "original", "title": "音"},
  {"id": ["c57", "39345yrozag4"], "category": "original", "title": "冬"},
  {"id": ["yvg", "26icziisqf1c"], "category": "original", "title": "遠心力その他もろもろ"},
  {"id": ["0of", "2cxxcdhn00r"], "category": "original", "title": "2011年賀"},
  {"id": ["hih", "5ky0cyf281og"], "category": "original", "title": "緊縛"},
  {"id": ["mit", "3gcx64tmax0k"], "category": "original", "title": "緊縛後日談"},
  {"id": ["zxb", "duvCka60SDac"], "category": "original", "title": "バランス"},
  {"id": ["lcp", "iUrivmU0fG2M"], "category": "original", "title": "ガーディアン"},
  {"id": ["833", "NqN8fdn70czf"], "category": "original", "title": "穴"},
  {"id": ["uby", "4gsouFZJtttL"], "category": "original", "title": "マフラー"},
  {"id": ["c62", "oTpnS150Ob5X"], "category": "original", "title": "2"},
  {"id": ["liy", "3IMSFLwmrAww"], "category": "original", "title": "沈む"},
  {"id": ["952", "Mq5Bd2uMkWt5"], "category": "original", "title": "無かった"},
  {"id": ["3on", "lNB7oTcCyD13"], "category": "original", "title": "untitled"},
  {"id": ["28d", "trx2K"], "category": "original", "title": "はいもしもし"},
  {"id": ["nlw", "MmdUO"], "category": "original", "title": "うさぎさん"},
  {"id": ["yr5", "CYZG72phbCsZ"], "category": "original", "title": "飛べると思った"},
  {"id": ["mer", "6lEoiGNJLrYS"], "category": "original", "title": "_"},
  {"id": ["duc", "qiiFa"], "category": "original", "title": "あたまかゆい"},
  {"id": ["tvp", "TFJw4"], "category": "original", "title": "ping-pong"},
  {"id": ["fb0", "2Jfyl"], "category": "original", "title": "おうち（兵器）"},
  {"id": ["x2p", "XuLj0"], "category": "original", "title": "しとしと"},
  {"id": ["jew", "h6gvj"], "category": "original", "title": "雨雲"},
  {"id": ["qrt", "okz", "iWw08"], "category": "original", "title": "バス停"},
  {"id": ["0tv", "BVLF1"], "category": "original", "title": "髪飾り"},
  {"id": ["v1e", "CXsFf"], "category": "original", "title": "箱"},
  {"id": ["hab", "22PhC"], "category": "original", "title": "上皿天秤"},
  {"id": ["xo0", "fdXKr"], "category": "original", "title": "公園"},
  {"id": ["vk0"], "category": "original", "title": "F"},
  {"id": ["mu4"], "category": "original", "title": "F"},
  {"id": ["ds8"], "category": "original", "title": "行かないの？"},
  {"id": ["e0I"], "category": "original", "title": ".."},
  {"id": ["2y3"], "category": "original", "title": "トンネル"},
  {"id": ["i9k"], "category": "original", "title": "通学"},
  {"id": ["ptf", "3rh717xqywow"], "category": "copyright", "title": "雪"},
  {"id": ["40e", "48ijrmo6xy04"], "category": "copyright", "title": "改変"},
  {"id": ["ta3", "6lxi8k07yf0g"], "category": "copyright", "title": "lain"},
  {"id": ["36j", "4b7kp6vu6wcg"], "category": "copyright", "title": "2009年賀"},
  {"id": ["a8u", "5x6m0tjybhss"], "category": "copyright", "title": "1"},
  {"id": ["k4e", "6axjezboq0sg"], "category": "copyright", "title": "プラグスーツ長門"},
  {"id": ["wy3", "5zpktmg4cxs0"], "category": "copyright", "title": "かがみん"},
  {"id": ["dxy", "pog2cez7b40"], "category": "copyright", "title": "めんま"},
  {"id": ["dfw", "dUwNC"], "category": "copyright", "title": "つかさ"},
  {"id": ["uu6", "5mbLQ"], "category": "copyright", "title": "A.B.A"},
  {"id": ["wii", "JLIAo"], "category": "copyright", "title": "五右衛門"},
  {"id": ["76g", "3izszlclco6c"], "category": "friend", "title": "えん×むさ"},
  {"id": ["dgs", "3vgrp75vvxyc"], "category": "friend", "title": "Djungarian Love Star"},
  {"id": ["86h", "6kdlqntxztog"], "category": "friend", "title": "okz"},
  {"id": ["r6v", "6vxulqkktlog"], "category": "friend", "title": "momoco"},
  {"id": ["s1b", "53328hvqzl0k"], "category": "friend", "title": "ひとめちゃん"},
  {"id": ["ms2", "tz1ov2pjvwg"], "category": "friend", "title": "ねこげ"},
  {"id": ["uor", "4mehl4f223uo"], "category": "graffiti", "title": "やばい、間違って屋上から包丁落としちゃった。"},
  {"id": ["6qt", "1hf5wga3izy8"], "category": "graffiti", "title": "エクトプラズム"},
  {"id": ["w7x", "4bswkwpfwk2s"], "category": "graffiti", "title": "お米擬人化"},
  {"id": ["s0d", "4usf03zqyc8w"], "category": "graffiti", "title": "横顔"},
];

export default config;
